In [1]:
import sklearn as sk

In [2]:
dir(sk)

['calibration',
 'clone',
 'cluster',
 'compose',
 'config_context',
 'covariance',
 'cross_decomposition',
 'datasets',
 'decomposition',
 'discriminant_analysis',
 'dummy',
 'ensemble',
 'exceptions',
 'experimental',
 'externals',
 'feature_extraction',
 'feature_selection',
 'frozen',
 'gaussian_process',
 'get_config',
 'impute',
 'inspection',
 'isotonic',
 'kernel_approximation',
 'kernel_ridge',
 'linear_model',
 'manifold',
 'metrics',
 'mixture',
 'model_selection',
 'multiclass',
 'multioutput',
 'naive_bayes',
 'neighbors',
 'neural_network',
 'pipeline',
 'preprocessing',
 'random_projection',
 'semi_supervised',
 'set_config',
 'show_versions',
 'svm',
 'tree']

In [3]:
from sklearn import datasets
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_file',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard

In [4]:
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()
california

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 

In [5]:
dir(california)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [6]:
from sklearn.datasets import fetch_california_housing
california=fetch_california_housing(as_frame=True)
california_df=california['frame']
california_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847


In [7]:
california_df.to_csv("california_df.csv")

In [8]:
x=california_df.drop('MedHouseVal',axis=1)
y=california_df['MedHouseVal']

In [9]:
california_df.info

<bound method DataFrame.info of        MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       

In [10]:
california_df.shape

(20640, 9)

In [11]:
california_df.isnull().sum()

MedInc         0
HouseAge       0
AveRooms       0
AveBedrms      0
Population     0
AveOccup       0
Latitude       0
Longitude      0
MedHouseVal    0
dtype: int64

In [12]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data=[]
for i in range (len(x.columns)):
    vif_data.append(variance_inflation_factor(x.values,i))
vif_data

[np.float64(11.511140059486932),
 np.float64(7.195917300645759),
 np.float64(45.99360103802389),
 np.float64(43.59031403163056),
 np.float64(2.935745199687899),
 np.float64(1.0952432155971743),
 np.float64(559.8740713791312),
 np.float64(633.7116543669108)]

In [13]:
import pandas as pd
vif_df=pd.DataFrame(vif_data,columns=["VIF"],index=x.columns)

In [14]:
vif_df

,VIF
MedInc,11.511140
HouseAge,7.195917
AveRooms,45.993601
AveBedrms,43.590314
Population,2.935745
AveOccup,1.095243
Latitude,559.874071
Longitude,633.711654


In [15]:
con1=vif_df[vif_df['VIF']<15].index
con1=con1.to_list()

In [16]:
con1

['MedInc', 'HouseAge', 'Population', 'AveOccup']

In [17]:
con2=vif_df[vif_df['VIF']>15].index
con2=con2.to_list()
con2

['AveRooms', 'AveBedrms', 'Latitude', 'Longitude']

In [18]:
con2=["AveRooms","Latitude"]

In [19]:
final_con=con1+con2
final_con

['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveRooms', 'Latitude']

In [20]:
import warnings
warnings.filterwarnings('ignore')
final_df=x[final_con]
final_df['MedHouseVal']=y
final_df

,MedInc,HouseAge,Population,AveOccup,AveRooms,Latitude,MedHouseVal
0,8.3252,41.0,322.0,2.555556,6.984127,37.88,4.526
1,8.3014,21.0,2401.0,2.109842,6.238137,37.86,3.585
2,7.2574,52.0,496.0,2.802260,8.288136,37.85,3.521
3,5.6431,52.0,558.0,2.547945,5.817352,37.85,3.413
4,3.8462,52.0,565.0,2.181467,6.281853,37.85,3.422
...,...,...,...,...,...,...,...
20635,1.5603,25.0,845.0,2.560606,5.045455,39.48,0.781
20636,2.5568,18.0,356.0,3.122807,6.114035,39.49,0.771
20637,1.7000,17.0,1007.0,2.325635,5.205543,39.43,0.923
20638,1.8672,18.0,741.0,2.123209,5.329513,39.43,0.847


In [21]:
x=final_df.drop('MedHouseVal',axis=1)
y=final_df['MedHouseVal']

In [22]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_scale=ss.fit_transform(x)
x_scale

array([[ 2.34476576,  0.98214266, -0.9744286 , -0.04959654,  0.62855945,
         1.05254828],
       [ 2.33223796, -0.60701891,  0.86143887, -0.09251223,  0.32704136,
         1.04318455],
       [ 1.7826994 ,  1.85618152, -0.82077735, -0.02584253,  1.15562047,
         1.03850269],
       ...,
       [-1.14259331, -0.92485123, -0.3695372 , -0.0717345 , -0.09031802,
         1.77823747],
       [-1.05458292, -0.84539315, -0.60442933, -0.09122515, -0.04021111,
         1.77823747],
       [-0.78012947, -1.00430931, -0.03397701, -0.04368215, -0.07044252,
         1.75014627]], shape=(20640, 6))

In [23]:
x_scale_df=pd.DataFrame(x_scale,columns=x.columns)

In [24]:
x_scale_df

,MedInc,HouseAge,Population,AveOccup,AveRooms,Latitude
0,2.344766,0.982143,-0.974429,-0.049597,0.628559,1.052548
1,2.332238,-0.607019,0.861439,-0.092512,0.327041,1.043185
2,1.782699,1.856182,-0.820777,-0.025843,1.155620,1.038503
3,0.932968,1.856182,-0.766028,-0.050329,0.156966,1.038503
4,-0.012881,1.856182,-0.759847,-0.085616,0.344711,1.038503
...,...,...,...,...,...,...
20635,-1.216128,-0.289187,-0.512592,-0.049110,-0.155023,1.801647
20636,-0.691593,-0.845393,-0.944405,0.005021,0.276881,1.806329
20637,-1.142593,-0.924851,-0.369537,-0.071735,-0.090318,1.778237
20638,-1.054583,-0.845393,-0.604429,-0.091225,-0.040211,1.778237


In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x_scale_df,y,test_size=0.2,random_state=12)

In [27]:
x_train.shape

(16512, 6)

In [28]:
y_train.shape

(16512,)

In [29]:
x_test.shape

(4128, 6)

In [30]:
y_test.shape

(4128,)

In [31]:
x_train.index

Index([ 1652, 14652,  3548,  6730, 18445, 10052, 10536,  8976,  9999,  5218,
       ...
       16261, 16308,   278, 12108,  9475,  3714,  7409, 19709,  5787, 14155],
      dtype='int64', length=16512)

In [32]:
y_train.index

Index([ 1652, 14652,  3548,  6730, 18445, 10052, 10536,  8976,  9999,  5218,
       ...
       16261, 16308,   278, 12108,  9475,  3714,  7409, 19709,  5787, 14155],
      dtype='int64', length=16512)

In [33]:
from sklearn.linear_model import LinearRegression

lr_model=LinearRegression()
lr_model.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [34]:
y_pred=lr_model.predict(x_test)

In [35]:
y_pred

array([2.5913592 , 1.5167858 , 2.24283693, ..., 1.12111776, 2.39057286,
       2.37078634], shape=(4128,))

In [36]:
from sklearn.metrics import r2_score,mean_squared_error

print(r2_score(y_test,y_pred))

0.533823375179216


In [37]:
lr_model.coef_

array([ 0.82992813,  0.22320023,  0.02622889, -0.04339881, -0.0442985 ,
       -0.09343038])

In [38]:
lr_model.intercept_

np.float64(2.066824931075249)

In [39]:
x.columns

Index(['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveRooms', 'Latitude'], dtype='object')

In [40]:
x_test.values[0]

array([ 0.25999332,  1.06160074, -0.02956174,  0.02119481, -0.0873985 ,
       -0.74528814])

In [41]:
import pickle

with open('Linear_regression_california.pkl','wb') as f:
    pickle.dump(lr_model,f)

print("model saved")

model saved


In [42]:
import  pickle

with open('Linear_regression_california.pkl','rb') as f:
    loaded_model=pickle.load(f)

In [43]:
loaded_model.coef_


array([ 0.82992813,  0.22320023,  0.02622889, -0.04339881, -0.0442985 ,
       -0.09343038])

In [44]:
loaded_model.intercept_

np.float64(2.066824931075249)